apiVersion: v1
kind: Service
metadata:
  name: hms-backend-service
spec:
  selector:
    app: hms-backend
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort   # So you can access your backend from browser
